// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLSpPBowN7_z8SKsQg6NRyckY2zeVWyo',
    appId: '1:704858090972:web:d982af5d589a13bb66f319',
    messagingSenderId: '704858090972',
    projectId: 'hyde-write',
    authDomain: 'hyde-write.firebaseapp.com',
    storageBucket: 'hyde-write.appspot.com',
    measurementId: 'G-91240R886Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgC8zp1t4LZSzJy_EdC29RAfK5SwShwGo',
    appId: '1:704858090972:android:37b39abe4fdc2ab366f319',
    messagingSenderId: '704858090972',
    projectId: 'hyde-write',
    storageBucket: 'hyde-write.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4roafFGkqZIPdjy6Cac9VqIqhsmNNfWw',
    appId: '1:704858090972:ios:17e44641d05a74c766f319',
    messagingSenderId: '704858090972',
    projectId: 'hyde-write',
    storageBucket: 'hyde-write.appspot.com',
    iosClientId:
        '704858090972-unn6iqrnt5u1v6h3spst62hv7mbr04g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.writeByHyde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4roafFGkqZIPdjy6Cac9VqIqhsmNNfWw',
    appId: '1:704858090972:ios:17e44641d05a74c766f319',
    messagingSenderId: '704858090972',
    projectId: 'hyde-write',
    storageBucket: 'hyde-write.appspot.com',
    iosClientId:
        '704858090972-unn6iqrnt5u1v6h3spst62hv7mbr04g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.writeByHyde',
  );
}
